### ISSUE TITLE
Failing test in v0.1.3 and v0.1.2

### ISSUE THREAD

**Issue by dwo** [nesquena/query_reviewer#7]
```
Started
.E
Finished in 0.000411 seconds.
1) Error:
test_analyze_select_type(SqlSubqueryTest):
ArgumentError: wrong number of arguments (1 for 0)
    /home/dwo/source/query_reviewer/test/sql_sub_query_test.rb:15:in `initialize'
    /home/dwo/source/query_reviewer/test/sql_sub_query_test.rb:15:in `new'
    /home/dwo/source/query_reviewer/test/sql_sub_query_test.rb:15:in `get_query'
    /home/dwo/source/query_reviewer/test/sql_sub_query_test.rb:5:in `test_analyze_select_type'

2 tests, 1 assertions, 0 failures, 1 errors
```

It looks like this has been a problem for at least the last two versions. When I run the tests for 0.1.1 I get another unrelated error.

**Comment by dwo** [comment]
If it's any help I'm running these on ubuntu (hardy) with REE 1.8.7, although these fails don't look to be environment specific.
